- package-lock.json
- package.json
- src/App.js
@joshson93 @amina197 @JonathanGhee
> Downgraded to react version 17

- src/RatingsReviews/index.js
> saving ratingsReviews

- src/App.js
- src/ProductDetails/index.js
- src/QandA/index.js
- src/RatingsReviews/index.js
- src/RelatedProducts/index.js
@Doobss @amina197 @JonathanGhee please review my code! Thanks
> render basic components

- src/App.js
- src/ProductDetails/index.js
- src/QandA/index.js
- src/RatingsReviews/index.js
- src/RelatedProducts/index.js
- src/api.js
@joshson93 
@amina197 
@JonathanGhee
> Refactored the initalization so that each module can define what data they need from any endpoint.

- src/QandA/Answers.js
- src/QandA/QAList.js
- src/QandA/Questions.js
- src/QandA/index.js
pretty much finished basic HTML structure, modularized my components, and made it so that users can click on "load more answers" to show 1 more answer per click.
@Doobss @amina197 @JonathanGhee
> Qand q html

- src/ProductDetails/index.js
- src/QandA/index.js
- src/RelatedProducts/components/Carousel.js
- src/RelatedProducts/components/RelatedCard.js
- src/RelatedProducts/index.js
- src/RelatedProducts/methods.js
- src/api.js
- src/appState/index.js
- src/appState/reducer.js
- src/index.css
Built the carousel component and can scroll through all of the related products. Also all of their images are rendered in their repective card.
> Main components for Related products are rendered.

- src/QandA/Answers.js
- src/QandA/index.js
@Doobss @amina197 @JonathanGhee see if the search functionality is all good!
> Search functionality of Q&A

- src/ProductDetails/index.js
- src/ProductDetails/productDesc.js
- src/ProductDetails/productFeatures.js
- src/ProductDetails/productInfo.js
@JonathanGhee @joshson93 @Doobss Could you please review? Many thanks!
> Display description and features

- src/QandA/Answers.js
- src/QandA/index.js
did not do any post reqs yet, but fixed button rendering in filtered and unfiltered lengths
@Doobss @amina197 @JonathanGhee
> fixed bugs dealing with rendering buttons. all should be good now.

- src/QandA/AnswerForm.js
- src/QandA/Answers.js
- src/QandA/ImageForm.js
- src/QandA/QAList.js
- src/QandA/QuestionForm.js
- src/QandA/Questions.js
- src/QandA/index.js
users can now send questions and answers to a specific questions.
> Post requests

- src/RatingsReviews/ReviewForm.js
- src/RatingsReviews/index.js
> added write Review modal popup

- src/ProductDetails/components/ProductInfo.js
- src/QandA/AnswerForm.js
@Doobss @JonathanGhee @joshson93  Could you please review? Thanks!
> Implement add to cart

- src/QandA/components/Questions.js
- src/QandA/components/forms/AnswerForm.js
- src/QandA/components/forms/ImageForm.js
- src/QandA/components/forms/QuestionForm.js
- src/QandA/index.js
most likely last commit before adding report modals or any bugs
> Animations

- src/App.js
- src/RatingsReviews/Rating.js
- src/RatingsReviews/index.js
- src/api/get.js
- src/appState/index.js
@Doobss @amina197 @joshson93  Please review. Had to add an additional review meta data request to the shared app files.
> Added search to Reviews. Added review meta data to the api get request

- src/RatingsReviews/Rating.js
- src/RatingsReviews/index.js
> hot fix on meta data. Will only render characteristics that exist

- src/RatingsReviews/Rating.js
- src/RatingsReviews/styles.css
> Implemented majority of ratings

- src/ProductDetails/components/ProductCarousel.js
- src/ProductDetails/components/ProductInfo.js
- src/ProductDetails/index.js
- src/ProductDetails/styles/Carousel.styled.js
- src/ProductDetails/styles/Flex.styled.js
- src/ProductDetails/styles/Overview.styled.js
- src/ProductDetails/styles/SizeQty.styled.js
- src/ProductDetails/styles/Styles.styled.js
@JonathanGhee @joshson93 @Doobss Could you please review? Thanks!
> Implement basic styled components + Handle Carousel Images Click

- src/QandA/components/Answers.js
- src/QandA/components/Questions.js
- src/QandA/components/forms/AnswerForm.js
- src/QandA/components/forms/QuestionForm.js
- src/QandA/index.js
> fixed few css bugs in Q&A

- src/RatingsReviews/Rating.js
- src/RatingsReviews/index.js
> saving work

- src/QandA/components/QAList.js
- src/QandA/components/Questions.js
- src/QandA/components/modals/ErrorModal.js
- src/QandA/index.js
added feature where the text searched can be customized to be highlighted or whatever. it is highlighted for now when searching for a question
> added where users can search and the searching text will be highlighted

- src/QandA/components/Answers.js
- src/QandA/components/Questions.js
- src/QandA/components/forms/AnswerForm.js
- src/QandA/components/forms/ImageForm.js
- src/QandA/components/forms/QuestionForm.js
- src/QandA/components/modals/ErrorModal.js
- src/QandA/components/modals/HelpfulModal.js
- src/QandA/components/modals/Image.js
- src/QandA/components/modals/ReportModal.js
- src/QandA/components/modals/SuccessModal.js
- src/appState/index.js
- src/appState/reducer.js
added "collapse" answers and made it so that localstorage holds all answers that user upvoted, so that they cannot upvote it again. this also fixed a bug where users could not upvote diff answers within the same question.
> Fixingbugs

- src/ProductDetails/components/ProductInfo.js
@Doobss , @joshson93 @JonathanGhee Could you please review? Many thanks!
> Fix bug on expandedView not updating when changing product

- src/ProductDetails/components/ProductCarousel.js
- src/ProductDetails/components/ProductInfo.js
- src/ProductDetails/styles/Carousel.styled.js
- src/ProductDetails/styles/ExpandedCarouselView.styled.js
@joshson93 @Doobss @JonathanGhee could you please review? Thanks!
> Fix expandedView bugs on style change, fix arrow carousel bugs

- src/ProductDetails/components/ProductCarousel.js
- src/ProductDetails/components/ProductInfo.js
- src/ProductDetails/styles/Carousel.styled.js
- src/ProductDetails/styles/ExpandedCarouselView.styled.js
- src/ProductDetails/styles/magnifier.css
@joshson93 @JonathanGhee @Doobss Could you please review? Many thanks!
> Implement zoom / glass magnifier on expanded viewcnot fully optimized

- src/RatingsReviews/Rating.js
- src/RatingsReviews/Review.js
- src/RatingsReviews/ReviewForm.js
- src/RatingsReviews/Star.js
- src/RatingsReviews/index.js
> adding review complete

- src/RatingsReviews/Rating.js
- src/RatingsReviews/Review.js
- src/RatingsReviews/ReviewForm.js
- src/RatingsReviews/Star.js
- src/RatingsReviews/index.js
>  fixed ratingsreview merged files

- src/RatingsReviews/Rating.js
- src/RatingsReviews/Review.js
- src/RatingsReviews/ReviewForm.js
- src/RatingsReviews/index.js
> ratings bar correctly positioned, fixed star filter click function
